language: java

jdk:
  - openjdk8

env:
  global:
    - PATH="$PATH:/usr/lib/dart/bin"
    - FORMAL_GIT_HUB_PAGES_AUTHOR: "spine-developers@teamdev.com"

before_install:
  - chmod +x gradlew
  - chmod +x config/scripts/register-ssh-key.sh

  # Install Dart, `pub`, and the `protoc_plugin` pub package.
  - chmod +x ./config/scripts/update-apt.sh
  - ./config/scripts/update-apt.sh
  - sudo apt-get install dart
  - pub global activate protoc_plugin

  # Decrypt and unpack credentials:
  #  - spine-dev.json - the Firebase service account to use for integration tests;
  #  - pub-credentials.json - credentials to publish package to Pub;
  #  - deploy_rsa_key - private key for deploying GitHub Pages.
  - openssl aes-256-cbc -K $encrypted_2930eb142dc7_key -iv $encrypted_2930eb142dc7_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
  - mkdir ./integration-tests/test-app/src/main/resources
  - mv ./spine-dev.json ./integration-tests/test-app/src/main/resources
  - mv ./pub-credentials.json $HOME/.pub-cache/credentials.json

script:
 - ./gradlew build --stacktrace
 - ./gradlew integrationTest

deploy:
  skip_cleanup: false
  provider: script
  script: bash config/publish-artifacts.sh
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
