language: java

jdk:
  - openjdk8

env:
  global:
    - PATH="$PATH:/usr/lib/dart/bin"
    - FORMAL_GIT_HUB_PAGES_AUTHOR: "spine-developers@teamdev.com"

before_install:
  - chmod +x gradlew
  - chmod +x config/scripts/register-ssh-key.sh

  # Install Dart, `pub`, and the `protoc_plugin` pub package.
  - chmod +x ./config/scripts/update-apt.sh
  - ./config/scripts/update-apt.sh
  - sudo apt-get install dart
  - pub global activate protoc_plugin
  - chmod +x ./script/unpack-credentials.sh
  - ./script/unpack-credentials.sh

script:
 - ./gradlew build --stacktrace
 - ./gradlew integrationTest

deploy:
  skip_cleanup: true
  provider: script
  script: bash config/scripts/publish-artifacts.sh
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
