name: dart_code_gen
description: A command line tool which generates Dart code for Protobuf type registries.
version: 0.1.3
homepage: https://spine.io

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.6.0
  protobuf: ^1.0.1
  fixnum: ^0.10.11
  code_builder: ^3.4.1
  dart_style: 1.3.6
  built_value: ^7.1.0
  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  dart_code_gen: main
