name: dart_code_gen
description: A command line tool which generates Dart code for Protobuf type registries.
version: 0.1.3
homepage: https://spine.io

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: 1.5.2
  protobuf: ^1.0.0
  fixnum: ^0.10.9
  code_builder: ^3.2.0
  dart_style: 1.3.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  dart_code_gen: main
