name: client_test
description: Tests for package `spine_client`.
publish_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  spine_client:
    path: ../../client

dev_dependencies:
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
