name: Build under Ubuntu

on:
  pull_request:
    branches:
      - master
      - 1.x-dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Activate Dart Protoc Plugin
        run: dart pub global activate protoc_plugin

      - name: Build with gradle
        run: ./gradlew build --stacktrace

      - name: Unpack credentials
        run:  >
          chmod +x ./script/unpack-credentials.sh
          && ./script/unpack-credentials.sh

      - name: Run integration tests
        run: ./gradlew integrationTest